### ISSUE TITLE
Total Amount Invested with Ticket of Size Chart (Critical!)

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/ico-transparency-monitor#39]
There seems to be a problem with this chart,  (Final one)
When Eth is set as a curruncie the sum of amount invested by all ticket sizes doesn't equal the amount of Eth invested

**Comment by rudolfix** [comment]
confirmed, we had a problem with assignment to last range in chart, @Moejoe90 thanks for reporting

**Comment by MostafaBalata** [comment]
Thanks for reporting, fixed in this pull request.
https://github.com/Neufund/ico-transparency-monitor/pull/42
